2024-08-13 23:15:23,707 - ERROR - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "E:\Проги\PytonProjects\TestProject\pythonProject1\Module12\HW4\Rtest.py", line 18, in test_run
    runner = Runner(123, 10)
             ^^^^^^^^^^^^^^^
  File "E:\Проги\PytonProjects\TestProject\pythonProject1\Module12\HW4\runner_and_tournament.py", line 7, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
2024-08-13 23:15:23,708 - ERROR - Неверная скорость для Runner
Traceback (most recent call last):
  File "E:\Проги\PytonProjects\TestProject\pythonProject1\Module12\HW4\Rtest.py", line 10, in test_walk
    runner = Runner("TestWalker", -5)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Проги\PytonProjects\TestProject\pythonProject1\Module12\HW4\runner_and_tournament.py", line 12, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
